import { db } from './index'

type Seed = [string, string, string, string, string, string, number | null, number | null, string, string, string, boolean, boolean, string, string, string, string]

const seed: Seed[] = [
  ['id', '대상자 번호', '기타', 'id', '', '', null, null, '', '', '', false, false, '', '', '', ''],
  ['occl', '하지동맥폐색 여부', '기타', 'categorical', '', '0=No|1=Yes', null, null, '', '', '', false, true, '', '', '', ''],
  ['occl_no', '하지동맥폐색 개수', '기타', 'integer', '', '', 0, 10, '', 'occl', '1', false, false, '', '', '', ''],
  ['amp_lt', '신체절단 여부', '기타', 'categorical', '', '0=절단받지않음|1=절단받음', null, null, '', '', '', false, true, '', '', '', ''],
  ['ampdt_lt', '신체절단일', '기타', 'datetime', 'yyyy-mm-dd', '', null, null, '', 'amp_lt', '1', false, false, '', '', '', ''],
  ['cc_lops', 'LOPS 증상 진단 여부', '기타', 'categorical', '', '0=없음|1=있음', null, null, '', '', '', false, true, '', '', '', ''],
  ['cc_pad', 'PAD 증상 여부', '기타', 'categorical', '', '0=없음|1=있음', null, null, '', '', '', false, true, '', '', '', ''],
  ['foot_deformity', '발변형 여부', '기타', 'categorical', '', '0=없음|1=있음', null, null, '', '', '', false, true, '', '', '', ''],
  ['학력', '발사이즈', '기타', 'character', '', '', null, null, '', '', '', false, false, '', '', '', ''],
  ['o', 'O', '기타', 'character', '', '', null, null, '', '', '', false, false, '', '', '', ''],
  ['sex', '성별', '기본정보 / 생활습관', 'categorical', '', '0=남자|1=여자', null, null, '', '', '', false, true, '', '', '', ''],
  ['age', '나이', '기본정보 / 생활습관', 'categorical', '', '1=20≤x<25|2=25≤x<30|3=30≤x<35|4=35≤x<40|5=40≤x<45|6=45≤x<50|7=50≤x<55|8=55≤x<60|9=60≤x<65|10=65≤x<70|11=70≤x<75|12=75≤x<80|13=80≤x<85|14=85≤x<90|15=90≤x', null, null, '', '', '', false, true, '', '', '', ''],
  ['edu', '학력', '기본정보 / 생활습관', 'categorical', '', '1=초졸|2=중졸|3=고졸|4=대졸|5=대학원이상', null, null, '', '', '', false, true, '', '', '', ''],
  ['dth', '사망여부', '기본정보 / 생활습관', 'categorical', '', '0=No|1=Yes', null, null, '', '', '', false, true, '', '', '', ''],
  ['dthdt', '사망일', '기본정보 / 생활습관', 'datetime', 'yyyy-mm-dd', '', null, null, '', 'dth', '1', false, false, '', '', '', ''],
  ['smk', '흡연여부', '기본정보 / 생활습관', 'categorical', '', '0=None or past-smoker|1=current smoker', null, null, '', '', '', false, true, '', '', '', ''],
  ['smdt', '흡연기간(년)', '기본정보 / 생활습관', 'real', '', '', 0, 200, '', 'smk', '*', true, false, '', '', '', ''],
  ['smkd', '하루 흡연량(개피), 1갑=20개피', '기본정보 / 생활습관', 'integer', '', '', 0, 200, '', 'smk', '*', true, false, '', '', '', ''],
  ['py', 'packyear(갑년)', '기본정보 / 생활습관', 'real', '', '', 0, 200, '', 'smk', '*', true, false, '', '', '', ''],
  ['exl', '신체활동여부', '신체활동', 'categorical', '', '0=No|1=Yes', null, null, '', '', '', false, true, '', '', '', ''],
  ['dfu', '당뇨발진단 여부', 'DFU 평가', 'categorical', '', '0=No|1=Yes', null, null, '', '', '', false, true, '', '', '', ''],
  ['wag', '당뇨발 Wagner grade', 'DFU 평가', 'categorical', '', '0=grade0|1=grade1|2=grade2|3=grade3|4=grade4|5=grade5', null, null, '', '', '', false, true, '', '', '', ''],
  ['snb_site', '당뇨발 SINBAD Site', 'DFU 평가', 'categorical', '', '0=No|1=Yes', null, null, '', '', '', false, true, '', '', '', ''],
  ['snb_isc', '당뇨발 SINBAD Ischemia', 'DFU 평가', 'categorical', '', '0=No|1=Yes', null, null, '', '', '', false, true, '', '', '', ''],
  ['snb_neuro', '당뇨발 SINBAD Neuropathy', 'DFU 평가', 'categorical', '', '0=No|1=Yes', null, null, '', '', '', false, true, '', '', '', ''],
  ['snb_bac', '당뇨발 SINBAD Baterical infection', 'DFU 평가', 'categorical', '', '0=No|1=Yes', null, null, '', '', '', false, true, '', '', '', ''],
  ['snb_area', '당뇨발 SINBAD area(size)', 'DFU 평가', 'categorical', '', '0=No|1=Yes', null, null, '', '', '', false, true, '', '', '', ''],
  ['snb_depth', '당뇨발 SINBAD depth', 'DFU 평가', 'categorical', '', '0=No|1=Yes', null, null, '', '', '', false, true, '', '', '', ''],
  ['snb_score', '당뇨발 SINBAD score', 'DFU 평가', 'integer', '', '', 0, 6, '', '', '', true, false, '', '', '', ''],
  ['dfu_wnd', '궤양여부', 'DFU 평가', 'categorical', '', '0=없음|1=있음', null, null, '', '', '', false, true, '', '', '', ''],
  ['dfu_no', '궤양 총 개수', 'DFU 평가', 'integer', '', '', 0, 100, '', 'dfu_wnd', '1', false, false, '', '', '', ''],
  ['dfu_ex_amt', '궤양의 특성-삼출물 여부', 'DFU 평가', 'categorical', '', '0=없음|1=있음', null, null, '', 'dfu_wnd', '1', false, true, '', '', '', ''],
  ['dfu_ex_type', '궤양의 특성-삼출물 성상', 'DFU 평가', 'categorical', '', '1=장액성|2=혈액성|3=혈정혈액성|4=화농성|5=기타', null, null, '','dfu_wnd,dfu_ex_amt','1,1',false,true,'','','',''],
  ['dfu_nrs', 'dfu-NRS', 'DFU 평가', 'integer', '', '', 0, 10, '', '', '', true, false, '', '', '', ''],
  ['map_lt', '좌측(L) 발 여부', 'DFU 평가', 'categorical', '', '0=없음|1=있음', null, null, '', 'dfu_wnd', '1', false, true, '', '', '', ''],
  ['map_rt', '우측(R) 발 여부', 'DFU 평가', 'categorical', '', '0=없음|1=있음', null, null, '', 'dfu_wnd', '1', false, true, '', '', '', ''],
  ['vdt', '진료기록일자', '과거력 / 진단', 'datetime', 'yyyy-mm-dd', '', null, null, '', '', '', false, false, '', '', '', ''],
  ['dfudt', '당뇨발 진단일', '과거력 / 진단', 'datetime', 'yyyy-mm-dd', '', null, null, '', 'dfu', '1', false, false, '', '', '', ''],
  ['dmdt', '당뇨 진단일', '과거력 / 진단', 'datetime', 'yyyy-mm-dd', '', null, null, '', '', '', false, false, '', '', '', ''],
  ['dmt', '당뇨 type', '과거력 / 진단', 'categorical', '', '1=1형|2=2형', null, null, '', 'dmdt', '*', false, true, '', '', '', ''],
  ['htn', '고혈압진단 여부', '과거력 / 진단', 'categorical', '', '0=진단받지않음|1=진단받음', null, null, '', '', '', false, true, '', '', '', ''],
  ['chd', '관상동맥질환 진단 여부', '과거력 / 진단', 'categorical', '', '0=진단받지않음|1=진단받음', null, null, '', '', '', false, true, '', '', '', ''],
  ['ckd', '만성콩팥질환 진단 여부', '과거력 / 진단', 'categorical', '', '0=진단받지않음|1=진단받음', null, null, '', '', '', false, true, '', '', '', ''],
  ['neph', '당뇨병성신증 진단여부', '과거력 / 진단', 'categorical', '', '0=진단받지않음|1=진단받음', null, null, '', '', '', false, true, '', '', '', ''],
  ['neur', '말초신경병증 진단여부', '과거력 / 진단', 'categorical', '', '0=진단받지않음|1=진단받음', null, null, '', '', '', false, true, '', '', '', ''],
  ['pvd', '말초동맥질환 진단 여부', '과거력 / 진단', 'categorical', '', '0=진단받지않음|1=진단받음', null, null, '', '', '', false, true, '', '', '', ''],
  ['esrd', 'ESRD 진단여부', '과거력 / 진단', 'categorical', '', '0=진단받지않음|1=진단받음', null, null, '', '', '', false, true, '', '', '', ''],
  ['hei', '키(cm)', '신체계측 / Vital', 'integer', '', '', 100, 500, '', '', '', false, false, '계측·혈압', 'number', '', ''],
  ['wei', '몸무게(kg)', '신체계측 / Vital', 'real', '', '', 10, 500, '', '', '', false, false, '계측·혈압', 'number', '', ''],
  ['bmi', 'BMI', '신체계측 / Vital', 'real', '', '', 10, 70, '', '', '', false, false, '계측·혈압', 'number', '', ''],
  ['sbp', 'SBP', '신체계측 / Vital', 'integer', '', '', 50, 300, '', '', '', false, false, '계측·혈압', 'number', '', ''],
  ['dbp', 'DBP', '신체계측 / Vital', 'integer', '', '', 30, 200, '', '', '', false, false, '계측·혈압', 'number', '', ''],
  ['lab', 'lab 검사 시행 여부', '검사결과', 'categorical', '', '0=검사 없음|1=검사 있음', null, null, '', '', '', false, false, '', '', '', ''],
  ['crp', 'CRP', '검사결과', 'character', '', '', 0, 500, '', '', '', false, false, '검사 결과', 'number', 'lab', '1'],
  ['toep', 'toe pressure', '검사결과', 'integer', '', '', 0, 200, '', '', '', true, false, '검사 결과', 'number', 'lab', '1'],
  ['fbs', 'FBS', '검사결과', 'integer', '', '', 20, 800, '', '', '', false, false, '검사 결과', 'number', 'lab', '1'],
  ['hba1c', 'HbA1c', '검사결과', 'character', '', '', 3, 20, '', '', '', false, false, '검사 결과', 'number', 'lab', '1'],
  ['glu', 'random plasma glucose', '검사결과', 'integer', '', '', 20, 1000, '', '', '', false, false, '검사 결과', 'number', 'lab', '1'],
  ['neutro', 'neutrophil percent', '검사결과', 'real', '', '', 0, 100, '', '', '', false, false, '검사 결과', 'number', 'lab', '1'],
  ['lympho', 'lymphocyte percent', '검사결과', 'real', '', '', 0, 100, '', '', '', false, false, '검사 결과', 'number', 'lab', '1'],
  ['esr', 'ESR', '검사결과', 'integer', '', '', 0, 150, '', '', '', false, false, '검사 결과', 'number', 'lab', '1'],
  ['alb', 'albumin', '검사결과', 'real', '', '', 1, 6, '', '', '', false, false, '검사 결과', 'number', 'lab', '1'],
  ['ua', 'uric acid', '검사결과', 'real', '', '', 1, 20, '', '', '', false, false, '검사 결과', 'number', 'lab', '1'],
  ['hb', 'Hb', '검사결과', 'real', '', '', 3, 25, '', '', '', false, false, '검사 결과', 'number', 'lab', '1'],
  ['hdl', 'HDL', '검사결과', 'integer', '', '', 5, 150, '', '', '', false, false, '검사 결과', 'number', 'lab', '1'],
  ['ldl', 'LDL', '검사결과', 'integer', '', '', 10, 400, '', '', '', false, false, '검사 결과', 'number', 'lab', '1'],
  ['tchol', 'total cholesterol', '검사결과', 'integer', '', '', 50, 600, '', '', '', false, false, '검사 결과', 'number', 'lab', '1'],
  ['abi', 'ABI(ankle-brachial index)', '검사결과', 'real', '', '', 0, 2, '', '', '', true, false, '', '', '', ''],
  ['angio', 'CT angiography 여부', '치료 / 약물 / 영상', 'categorical', '', '0=No|1=Yes', null, null, '', '', '', false, true, '', '', '', ''],
  ['pta', 'PTA (Percutaneous Transluminal Angioplasty) 여부', '치료 / 약물 / 영상', 'categorical', '', '0=No|1=Yes', null, null, '', '', '', false, true, '', '', '', ''],
  ['off', '당뇨발 감압치료 여부', '치료 / 약물 / 영상', 'categorical', '', '0=No|1=Yes', null, null, '', '', '', false, true, '', '', '', ''],
  ['abx', '항생제 사용여부', '치료 / 약물 / 영상', 'categorical', '', '0=No|1=Yes', null, null, '', '', '', false, true, '', '', '', ''],
  ['insulin', '인슐린사용 여부', '치료 / 약물 / 영상', 'categorical', '', '0=처방받은적없음|1=처방받은적있음', null, null, '', '', '', false, true, '', '', '', ''],
  ['dmm', '경구혈당강하제 사용 여부', '치료 / 약물 / 영상', 'categorical', '', '0=처방받은적없음|1=처방받은적있음', null, null, '', '', '', false, true, '', '', '', ''],
  ['img2d', '당뇨발 2D 이미지 EMR에 업로드 되어있는지 여부', '치료 / 약물 / 영상', 'categorical', '', '0=없음|1=있음', null, null, '', '', '', false, true, '', '', '', ''],
]

export function seedDatabase() {
  const insert = db().prepare(`INSERT INTO variable_definitions (variable_key,label,section,data_type,unit_or_format,category_options,min_value,max_value,na_rule_raw,parents,active_values,allow_blank,allow_unknown_99,group_name,group_type,group_parent,group_active_value,display_order) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(variable_key) DO NOTHING`)
  db().transaction(() => seed.forEach((item, index) => insert.run(item[0], item[1], item[2], item[3], item[4], item[5], item[6], item[7], item[8], item[9], item[10], item[11] ? 1 : 0, item[12] ? 1 : 0, item[13], item[14], item[15], item[16], index)))()
}

seedDatabase()