// Isolated integration checks: never open the workspace's clinical database.
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const assert = require('node:assert/strict')
const ts = require('typescript')
const Module = require('node:module')
const root = path.resolve(__dirname, '..')
const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'edc-crf-test-'))
process.env.EDC_DATA_DIR = directory
const resolve = Module._resolveFilename
Module._resolveFilename = function (name, ...args) {
  return resolve.call(this, name.startsWith('@/') ? path.join(root, name.slice(2)) : name, ...args)
}
require.extensions['.ts'] = (module, filename) => {
  module._compile(ts.transpileModule(fs.readFileSync(filename, 'utf8'), {
    compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2020, esModuleInterop: true },
  }).outputText, filename)
}

async function main() {
  const { db } = require('../lib/db/index.ts')
  require('../lib/db/seed.ts')
  const { GET, POST } = require('../app/api/subjects/[subjectId]/route.ts')
  const { NextRequest } = require('next/server')
  const context = { params: Promise.resolve({ subjectId: 'CRF_TEST' }) }
  const save = (data) => POST(new NextRequest('http://localhost/api/subjects/CRF_TEST', {
    method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ timepoint: 'T2', variableKey: 'occl', ...data }),
  }), context)
  const open = () => db().prepare("SELECT * FROM queries WHERE status='OPEN'").all()
  assert.equal((await save({ value: '8' })).status, 200)
  assert.equal(open()[0].query_type, 'CATEGORY')
  assert.equal((await save({ value: '99' })).status, 200)
  assert.equal(open().length, 0, 'Existing Unknown 99 remains valid')
  await save({ value: null, missingReason: 'NOT_DONE' })
  const detail = await (await GET(new NextRequest('http://localhost'), context)).json()
  assert.equal(detail.values[0].value, null)
  assert.equal(detail.values[0].missingReason, 'NOT_DONE')
  assert.equal(open().length, 0)
  const exported = await require('../app/api/export/route.ts').GET(new NextRequest('http://localhost/api/export?subject=CRF_TEST'))
  const xlsx = require('xlsx')
  const workbook = xlsx.read(Buffer.from(await exported.arrayBuffer()))
  assert.equal(xlsx.utils.sheet_to_json(workbook.Sheets.data)[0].occl_t2_missing_reason, 'NOT_DONE')
  assert.deepEqual(workbook.SheetNames, ['data', 'Variable Dictionary'])
  const helpers = require('../lib/clinical-utils.ts')
  assert.deepEqual(helpers.sortSubjectsNumerically(['10', '2', '1', '3'].map((id) => ({ subject_id: 'Subject ' + id }))).map((s) => s.subject_id), ['Subject 1', 'Subject 2', 'Subject 3', 'Subject 10'])
  assert.equal(helpers.getSubjectQueryStatus([{ status: 'OPEN' }, { status: 'RESOLVED' }]), 'OPEN')
  assert.equal(helpers.getSubjectQueryStatus([]), 'RESOLVED')
  assert.equal(helpers.getSubjectQueryStatus([{ status: 'RESOLVED' }]), 'RESOLVED')
  const auth = require('../app/api/admin/auth/route.ts').POST
  for (const [password, expected] of [['incorrect', 401], ['123456', 200]]) {
    assert.equal((await auth(new Request('http://localhost/api/admin/auth', { method: 'POST', body: JSON.stringify({ password }) }))).status, expected)
  }
  assert.equal((await (await require('../app/api/admin/status/route.ts').GET()).json()).isAdmin, false)
  const exportApi = require('../app/api/export/route.ts').GET
  const scoped = await exportApi(new NextRequest('http://localhost/api/export?subject=CRF_TEST&visit=T1'))
  const scopedBook = xlsx.read(Buffer.from(await scoped.arrayBuffer()))
  assert.equal(xlsx.utils.sheet_to_json(scopedBook.Sheets.data)[0].occl_t2_missing_reason, undefined)
  assert.deepEqual(scopedBook.SheetNames, ['data', 'Variable Dictionary'])
  const history = await (await exportApi(new NextRequest('http://localhost/api/export?history=1'))).json()
  assert.equal(history[0].visit, 'T1')
  assert.equal(history[0].subject_id, 'CRF_TEST')
  assert.equal(history[0].status, 'Completed')
  assert.ok(history[0].id > history[1].id)
  const beforeInvalid = history.length
  assert.equal((await exportApi(new NextRequest('http://localhost/api/export?visit=T9'))).status, 400)
  assert.equal((await (await exportApi(new NextRequest('http://localhost/api/export?history=1'))).json()).length, beforeInvalid)
  const auditApi = require('../app/api/audit/route.ts').GET
  const auditRows = await auditApi(new NextRequest('http://localhost/api/audit?subjectId=CRF_TEST&visit=T1&action=EXPORT&from=2000-01-01&to=2100-01-01')).json()
  assert.equal(auditRows.length, 1)
  assert.equal(auditRows[0].action, 'EXPORT')
  console.log('PASS: natural sorting, derived status, password validation, unauthenticated status, scoped export, persistent newest-first history, invalid export exclusion, combined audit filters')
  assert.equal((await save({ value: '1', missingReason: 'NOT_DONE' })).status, 400)
  assert.equal((await save({ value: null, missingReason: 'INVALID' })).status, 400)
  assert.equal((await save({ timepoint: 'T4', value: '1' })).status, 400)
  await save({ value: '' })
  assert.equal(open()[0].query_type, 'MISSING', 'Clearing a reason restores required validation')
  await save({ value: '1' })
  assert.equal(open().length, 0)
  await save({ variableKey: 'occl_no', value: '11' })
  assert.equal(open()[0].query_type, 'RANGE')
  await save({ variableKey: 'occl_no', value: '5' })
  assert.equal(open().length, 0)
  await save({ variableKey: 'vdt', value: '2026-09-17' })
  assert.equal(db().prepare("SELECT visit_date FROM visits WHERE timepoint='T2'").get().visit_date, '2026-09-17')
  const audits = db().prepare('SELECT * FROM audit_logs').all()
  assert.ok(audits.some((row) => row.new_value.includes('NOT_DONE')))
  const { categoryChoices, inputGuide } = require('../lib/crf-metadata.ts')
  const rule = { variableKey: 'occl', dataType: 'categorical', categoryOptions: '0=없음|1=있음', allowUnknown99: true, inputGuide: '' }
  assert.deepEqual(categoryChoices(rule).map((choice) => choice.code), ['0', '1', '99'])
  assert.match(inputGuide(rule), /1=있음/)
  const { isVisitComplete, getDataEntrySummary } = require('../lib/data-entry.ts')
  const { rowToVariable, ensureSubject } = require('../lib/db/index.ts')
  const baseRule = rowToVariable({ variable_key: 'required', label: 'Required', section: 'Test', data_type: 'character', enabled: 1, timepoint_t1: 1, timepoint_t2: 1, timepoint_t3: 1 })
  const value = (variableKey, value, missingReason) => ({ variableKey, value, missingReason })
  for (const blank of ['', '  ', null, undefined]) assert.equal(isVisitComplete('A', 'T1', [baseRule], [value('required', blank)]), false)
  assert.equal(isVisitComplete('A', 'T1', [baseRule], [value('required', '0')]), true)
  assert.equal(isVisitComplete('A', 'T1', [baseRule], [value('required', null, 'NOT_DONE')]), false)
  assert.equal(isVisitComplete('A', 'T1', [baseRule], [value('required', null, 'INVALID')]), false)
  assert.equal(isVisitComplete('A', 'T1', [{ ...baseRule, allowBlank: true }], []), true)
  assert.equal(isVisitComplete('A', 'T1', [baseRule, { ...baseRule, variableKey: 'disabled', enabled: false }], [value('required', '0')]), true)
  assert.equal(isVisitComplete('A', 'T1', [baseRule, { ...baseRule, variableKey: 't2only', timepointT1: false }], [value('required', '0')]), true)
  const child = { ...baseRule, variableKey: 'child', parents: 'required', activeValues: '1' }
  assert.equal(isVisitComplete('A', 'T1', [baseRule, child], [value('required', '0')]), true)
  assert.equal(isVisitComplete('A', 'T1', [baseRule, child], [value('required', '1')]), false)
  assert.equal(isVisitComplete('A', 'T1', [baseRule, child], [value('required', '1'), value('child', 'entered')]), true)
  const groupChild = { ...child, parents: '', groupParent: 'required', groupActiveValue: '1' }
  assert.equal(isVisitComplete('A', 'T1', [baseRule, groupChild], [value('required', '0')]), true)
  assert.equal(isVisitComplete('A', 'T1', [baseRule, groupChild], [value('required', '1')]), false)
  assert.equal(isVisitComplete('A', 'T1', [{ ...baseRule, dataType: 'id' }], []), true)
  const { getSubjectVisitProgress, hasEntryValue } = require('../lib/data-entry.ts')
  const { getVisitVariables } = require('../lib/visit-rules.ts')
  assert.equal(hasEntryValue(0), true)
  assert.equal(hasEntryValue(false), true)
  assert.equal(hasEntryValue('  '), false)
  const t1Only = { ...baseRule, variableKey: 'baseline_only', timepointT2: false, timepointT3: false }
  const progressRules = [baseRule, t1Only]
  assert.equal(getVisitVariables(progressRules, 'T1').length, 2)
  assert.equal(getVisitVariables(progressRules, 'T2').length, 1)
  assert.equal(getVisitVariables(progressRules, 'T3').length, 1)
  assert.deepEqual(getSubjectVisitProgress('A', 'T1', progressRules, [value('required', 0)]), { completed: 1, total: 2, percentage: 50, complete: false })
  assert.equal(getSubjectVisitProgress('A', 'T2', progressRules, [value('required', false)]).percentage, 100)
  assert.equal(getSubjectVisitProgress('A', 'T3', progressRules, []).percentage, 0)
  db().prepare("UPDATE variable_definitions SET timepoint_t2=0,timepoint_t3=0 WHERE variable_key='occl_no'").run()
  const valueCount = db().prepare('SELECT COUNT(*) AS count FROM clinical_values').get().count
  const auditCount = db().prepare('SELECT COUNT(*) AS count FROM audit_logs').get().count
  assert.equal((await save({ variableKey: 'occl_no', timepoint: 'T2', value: '3' })).status, 400)
  assert.equal((await save({ variableKey: 'occl_no', timepoint: 'T3', value: '3' })).status, 400)
  assert.equal(db().prepare('SELECT COUNT(*) AS count FROM clinical_values').get().count, valueCount)
  assert.equal(db().prepare('SELECT COUNT(*) AS count FROM audit_logs').get().count, auditCount)
  assert.equal((await save({ variableKey: 'occl_no', timepoint: 'T1', value: '3' })).status, 200)
  const patchRule = require('../app/api/variables/[variableKey]/route.ts').PATCH
  await patchRule(new Request('http://localhost/api/variables/occl_no', { method: 'PATCH', body: JSON.stringify({ inputGuide: 'Visit restriction test' }) }), { params: Promise.resolve({ variableKey: 'occl_no' }) })
  assert.equal(db().prepare("SELECT timepoint_t2 FROM variable_definitions WHERE variable_key='occl_no'").get().timepoint_t2, 0)
  const auditWithoutUser = await auditApi(new NextRequest('http://localhost/api/audit?subjectId=CRF_TEST&visit=T1&action=EXPORT&user=does-not-exist')).json()
  assert.equal(auditWithoutUser.length, 1)
  assert.equal(auditWithoutUser[0].modified_by, 'Minji Jung')
  console.log('PASS: partial subject progress, zero/false values, visit-specific denominator, T1-only API restriction, metadata edit preservation, user filter removal')
  const emptySummary = getDataEntrySummary([])
  assert.equal(emptySummary.complete + emptySummary.incomplete, 0)
  assert.ok(emptySummary.visits.every((v) => v.percentage === 0))

  // Exercise the real subjects endpoint against saved rows, independently of queries.
  const completeSubject = ensureSubject('COMPLETE_TEST')
  ensureSubject('EMPTY_TEST')
  const definitions = db().prepare('SELECT * FROM variable_definitions WHERE enabled=1 AND allow_blank=0').all()
  const insertValue = db().prepare('INSERT INTO clinical_values(subject_id,visit_id,variable_key,value) VALUES(?,?,?,?)')
  db().transaction(() => {
    for (const visit of db().prepare('SELECT * FROM visits WHERE subject_id=?').all(completeSubject.id)) {
      for (const rule of definitions) {
        if (rule.data_type !== 'id') insertValue.run(completeSubject.id, visit.id, rule.variable_key, '0')
      }
    }
  })()
  const subjectsApi = require('../app/api/subjects/route.ts').GET
  let subjectsData = await subjectsApi().json()
  assert.deepEqual(subjectsData.find((s) => s.subject_id === 'COMPLETE_TEST').visit_completion, { T1: true, T2: true, T3: true })
  assert.deepEqual(subjectsData.find((s) => s.subject_id === 'EMPTY_TEST').visit_completion, { T1: false, T2: false, T3: false })
  let summary = getDataEntrySummary(subjectsData)
  assert.ok(subjectsData.find((s) => s.subject_id === 'COMPLETE_TEST').visit_progress.T1.total > 0)
  assert.equal(subjectsData.find((s) => s.subject_id === 'COMPLETE_TEST').visit_progress.T1.percentage, 100)
  assert.equal(summary.complete, 1)
  assert.equal(summary.complete + summary.incomplete, summary.total)
  assert.deepEqual(summary.visits.map((v) => v.completed), [1, 1, 1])
  db().prepare("UPDATE clinical_values SET value='' WHERE subject_id=? AND variable_key='occl' AND visit_id=(SELECT id FROM visits WHERE subject_id=? AND timepoint='T2')").run(completeSubject.id, completeSubject.id)
  subjectsData = await subjectsApi().json()
  summary = getDataEntrySummary(subjectsData)
  assert.equal(summary.complete, 0)
  assert.equal(summary.incomplete, summary.total)
  assert.deepEqual(summary.visits.map((v) => v.completed), [1, 0, 1])
  assert.equal(summary.visits[0].percentage, Math.round(100 / summary.total))

  const { readPageAccess, pageSessionKeys } = require('../lib/page-access.ts')
  const session = new Map([['edc-admin', 'true']])
  const storage = { getItem: (key) => session.get(key) || null, removeItem: (key) => session.delete(key) }
  assert.deepEqual(readPageAccess(storage), { 'Rule Master': false, 'Audit Trail': false })
  session.set(pageSessionKeys['Rule Master'], JSON.stringify({ authenticatedAt: Date.now() }))
  assert.deepEqual(readPageAccess(storage), { 'Rule Master': true, 'Audit Trail': false })
  session.clear(); session.set(pageSessionKeys['Audit Trail'], JSON.stringify({ authenticatedAt: Date.now() }))
  assert.deepEqual(readPageAccess(storage), { 'Rule Master': false, 'Audit Trail': true })
  session.clear()
  assert.deepEqual(readPageAccess(storage), { 'Rule Master': false, 'Audit Trail': false })
  const { ADMIN_AUTH_TTL_MS } = require('../lib/admin-auth-config.ts')
  const now = Date.now()
  session.set(pageSessionKeys['Rule Master'], JSON.stringify({ authenticatedAt: now }))
  session.set(pageSessionKeys['Audit Trail'], JSON.stringify({ authenticatedAt: now + 1000 }))
  assert.equal(readPageAccess(storage, now + ADMIN_AUTH_TTL_MS - 1)['Rule Master'], true)
  assert.deepEqual(readPageAccess(storage, now + ADMIN_AUTH_TTL_MS), { 'Rule Master': false, 'Audit Trail': true })
  assert.equal(session.has(pageSessionKeys['Rule Master']), false)
  assert.equal(readPageAccess(storage, now + ADMIN_AUTH_TTL_MS + 1000)['Audit Trail'], false)
  for (const invalid of ['true', '{', JSON.stringify({ authenticatedAt: now + 1000 })]) {
    session.set(pageSessionKeys['Rule Master'], invalid)
    assert.equal(readPageAccess(storage, now)['Rule Master'], false)
    assert.equal(session.has(pageSessionKeys['Rule Master']), false)
  }
  console.log('PASS: exact XLSX sheet order, required/optional/conditional/visit-specific completion, missing reasons, persisted dashboard counts and progress, independent page sessions')
  const dateTime = require('../lib/date-time.ts')
  assert.equal(dateTime.parseTimestamp('2026-09-14 06:20:30').toISOString(), '2026-09-14T06:20:30.000Z')
  assert.equal(dateTime.parseTimestamp('2026-09-14T06:20:30.123Z').toISOString(), '2026-09-14T06:20:30.123Z')
  assert.match(dateTime.formatDateTime('2026-09-14 06:20:30', 'Asia/Seoul'), /15:20:30/)
  assert.match(dateTime.formatDateTime('2026-09-14T06:20:30Z', 'UTC'), /06:20:30/)
  const aggregate = require('../lib/data-entry.ts').getAggregateFieldProgress
  const stats = (completed,total) => ({ completed,total,percentage:0,complete:false })
  const a = { visit_progress: { T1:stats(1,2),T2:stats(0,0),T3:stats(0,2) } }
  const b = { visit_progress: { T1:stats(9,98),T2:stats(1,3),T3:stats(1,2) } }
  assert.deepEqual(aggregate([a,b]).T1, { completed:10,total:100,percentage:10 })
  assert.deepEqual(aggregate([a,b]).T2, { completed:1,total:3,percentage:33 })
  assert.deepEqual(aggregate([]).T1, { completed:0,total:0,percentage:0 })
  assert.deepEqual(aggregate([a,b]).T3, { completed:1,total:4,percentage:25 })
  const subjectBefore = db().prepare("SELECT created_at,updated_at FROM subjects WHERE subject_id='CRF_TEST'").get()
  ensureSubject('CRF_TEST')
  assert.deepEqual(db().prepare("SELECT created_at,updated_at FROM subjects WHERE subject_id='CRF_TEST'").get(), subjectBefore, 'Opening a subject does not change timestamps')
  const auditBefore = db().prepare('SELECT id,modified_at FROM audit_logs').all()
  const startTime = Date.now()
  const savedResponse = await save({ variableKey:'occl', value:'8' })
  const savedPayload = await savedResponse.json()
  assert.ok(Date.parse(savedPayload.savedAt) >= startTime && Date.parse(savedPayload.savedAt) <= Date.now())
  const savedSubject = db().prepare("SELECT created_at,updated_at FROM subjects WHERE subject_id='CRF_TEST'").get()
  assert.equal(savedSubject.created_at,subjectBefore.created_at)
  assert.equal(savedSubject.updated_at,savedPayload.savedAt)
  assert.equal(db().prepare("SELECT modified_at FROM clinical_values WHERE variable_key='occl' AND subject_id=(SELECT id FROM subjects WHERE subject_id='CRF_TEST')").get().modified_at,savedPayload.savedAt)
  assert.equal(db().prepare("SELECT updated_at FROM queries WHERE subject_id='CRF_TEST' AND variable_key='occl' AND status='OPEN'").get().updated_at,savedPayload.savedAt)
  for (const row of auditBefore) assert.equal(db().prepare('SELECT modified_at FROM audit_logs WHERE id=?').get(row.id).modified_at,row.modified_at)
  const oldDetected = db().prepare("SELECT detected_at FROM queries WHERE subject_id='CRF_TEST' AND variable_key='occl' AND status='OPEN'").get().detected_at
  const resolvedPayload = await (await save({ variableKey:'occl',value:'0' })).json()
  const resolvedQuery = db().prepare("SELECT detected_at,updated_at,resolved_at FROM queries WHERE subject_id='CRF_TEST' AND variable_key='occl' AND query_type='CATEGORY'").get()
  assert.equal(resolvedQuery.detected_at,oldDetected)
  assert.equal(resolvedQuery.resolved_at,resolvedPayload.savedAt)
  assert.equal(resolvedQuery.updated_at,resolvedPayload.savedAt)
  const refreshedDetail = await (await GET(new NextRequest('http://localhost'),context)).json()
  assert.equal(refreshedDetail.savedAt,resolvedPayload.savedAt)
  const exportedTime = history[0].exported_at
  assert.ok(exportedTime.endsWith('Z'))
  db().prepare("INSERT INTO audit_logs(subject_id,modified_at,action) VALUES('TZ_TEST','2026-09-13 15:00:00','UPDATE'),('TZ_TEST','2026-09-14T15:00:00.000Z','UPDATE')").run()
  const timezoneRows = await auditApi(new NextRequest('http://localhost/api/audit?subjectId=TZ_TEST&fromInstant=2026-09-13T15:00:00Z&toInstant=2026-09-14T15:00:00Z')).json()
  assert.equal(timezoneRows.length,1)
  assert.equal(timezoneRows[0].modified_at,'2026-09-13 15:00:00')
  console.log('PASS: field-weighted aggregate progress, UTC/SQLite/KST formatting, actual server save times, read-only open, query lifecycle timestamps, historical audit preservation')
  db().prepare("INSERT INTO queries(subject_id,timepoint,variable_key,query_type,message,status) VALUES('CRF_TEST','T1','occl','EXPORT_TEST','Export scope test','ARCHIVED')").run()
  for (const scope of ['', 'subject=CRF_TEST', 'subject=CRF_TEST&visit=T1', 'visit=T2']) {
    const response = await exportApi(new NextRequest(`http://localhost/api/export?${scope}${scope ? '&' : ''}includeQueries=1`))
    assert.equal(response.status, 200)
    const book = xlsx.read(Buffer.from(await response.arrayBuffer()))
    assert.deepEqual(book.SheetNames, ['data', 'Variable Dictionary', 'Queries'])
    const rows = xlsx.utils.sheet_to_json(book.Sheets.Queries)
    const filters = new URLSearchParams(scope)
    const expected = db().prepare('SELECT * FROM queries').all().filter((row) => (!filters.get('subject') || row.subject_id === filters.get('subject')) && (!filters.get('visit') || row.timepoint === filters.get('visit')))
    assert.equal(rows.length, expected.length)
    assert.ok(rows.every((row) => ['OPEN', 'RESOLVED'].includes(row.Status)))
    assert.ok(rows.every((row) => !filters.get('subject') || row['Subject ID'] === filters.get('subject')))
    assert.ok(rows.every((row) => !filters.get('visit') || row.Visit === filters.get('visit')))
  }
  const latestExport = await (await exportApi(new NextRequest('http://localhost/api/export?history=1'))).json()
  assert.equal(latestExport[0].export_type, 'XLSX + Queries')
  const off = await exportApi(new NextRequest('http://localhost/api/export?includeQueries=0'))
  assert.deepEqual(xlsx.read(Buffer.from(await off.arrayBuffer())).SheetNames, ['data', 'Variable Dictionary'])
  console.log('PASS: optional Queries sheet, all/subject/visit scope, normalized statuses, no Audit sheet, export history, independent TTL expiry and invalid auth rejection')
  db().close()
  console.log('PASS: category / 99, missing round-trip, conflict rejection, query resolution, range, visit date, audit, export, metadata')
}
main().catch((error) => { console.error(error); process.exitCode = 1 }).finally(() => {
  // Keep the isolated directory for inspection; no recursive cleanup of user paths.
  console.log(`Test database: ${directory}`)
})
